### ISSUE TITLE
About the testing dataset.

### ISSUE THREAD

**Issue by hustzxd** [luost26/DMRDenoise#10]
Thanks for the wonderful job.
However, as a beginner, there is a question that confuses me.

There are only the following four folders in the compressed package `dataset_test.zip`. Could you please share the clean data `input_full_test_50k` without noise?
```bash
input_full_test_50k_0.010  
input_full_test_50k_0.020  
input_full_test_50k_0.025  
input_full_test_50k_0.030
```

**Comment by luost26** [comment]
Hi,

Please find the ground truth point clouds here:
https://drive.google.com/file/d/1D7F0QUaMnj31y1EKFuqj5-SRmXTBHp20/view?usp=sharing
`.xyz` files are point clouds. `.normal` files are point-wise normal vectors.

**Comment by hustzxd** [comment]
Got it, thank you!
