### ISSUE TITLE
How to get normals?

### ISSUE THREAD

**Issue by zxy110** [luost26/DMRDenoise#11]
Hi,

Thanks for your great work and detailed code. 
I want to test the point-to-surface results, and I find it needs normals as input.
Could you please tell me how you obtain the normals (used in the p2s loss function) ? 

Thanks a lot.

**Comment by luost26** [comment]
You may make point clouds with normal vectors from your own meshes.

Here is a convenient tool for generating point clouds with normal vectors from meshes:
https://github.com/fwilliams/point-cloud-utils

**Comment by zxy110** [comment]
Sovled, thank you!
