### ISSUE TITLE
P2S distance

### ISSUE THREAD

**Issue by ia-usami** [luost26/DMRDenoise#12]
Hi, I want to use point-to-surface distance, but I am confused with the formula and could not find the implementation code.
If I understand it correctly, the point q on surface S is refered to the cloest point to p on S, with the surface S is defined by vertices of mesh. In this way, the mesh data are necessary for calculating P2S distance. However, the mesh data currently is not released along with this repo.
Can you give me some detail about how this metric is calculated, or any similar implementaion code.
It would be better, if you can release the corresponding code and mesh.

**Comment by ia-usami** [comment]
@luost26

**Comment by ia-usami** [comment]
Hi, I try to implement P2S distance by myself and pick the corresponding mesh from ModelNet40 by mesh naming for evaluation. However, the raw mesh must be normalized before calculating P2S. I have tried to implement the normalization, but still failed to fit the mesh to ground truth points.
Can you release the mesh normalization code or the normalized mesh, so that I can make the next step ?

**Comment by luost26** [comment]
Hi

sorry for the late reply. I am super busy recently.

you may estimate P2S using points and normals. they can be found here: https://drive.google.com/file/d/1D7F0QUaMnj31y1EKFuqj5-SRmXTBHp20/view?usp=sharing

**Comment by ia-usami** [comment]
I need to confirm the last problem:
Which is the surface defination used in P2S distance ? (A, B, or C)
A. A face in triangulated mesh by 3 vertices.
B. The point-Normal Form of a plane.
C. Others
