### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'hparams'

### ISSUE THREAD

**Issue by ghost** [luost26/DMRDenoise#13]
Hi nice to meet you luost!
I'm student who is majoring in computer science.

First of all, your works are very awsome.
I'm trying to run the pretrained model with my rtx 3090.
But the cuda toolkit (nvcc) version which you are suggesting doesn't match with my GPU, so i find out that my GPU needs cuda toolkit 11.0 <= , and i installed it instead of 10.0

here is the problem occurs...

pytorch-lightning version 0.7.6 which you are suggesting doesn't support cuda toolkik 11.0
so, i installed pytorch-lightning 1.4.5.

However, when i load your pretrained model "./pretrained/supervised/epoch=153.ckpt" on my command,
it has error...like this.
<img width="1223" alt="스크린샷 2021-09-03 오후 5 27 34" src="https://user-images.githubusercontent.com/73864163/131975183-5d3e5ffa-6afa-454f-bd70-a4d0bfb03eb9.png">

and I have searched and agonized over the problem, i guess that the cause is the version of pytorch-lightning.

Do you have any solution for my environment?

your denosing method is really remarkable.
I want to run the model so much....

their are my packages of venv!
<img width="1223" alt="스크린샷 2021-09-03 오후 5 32 56" src="https://user-images.githubusercontent.com/73864163/131975853-21f0526e-707b-42e9-9925-b80b50c06631.png">
 
Thank you!

**Comment by ghost** [comment]
oh, I fixed it by `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge` and conda-forge helps it install python-lightning 0.7.6! 

Thank you!

**Comment by luost26** [comment]
Thank you for being helpful!
