### ISSUE TITLE
size of tensors must match

### ISSUE THREAD

**Issue by alavona** [luost26/DMRDenoise#14]
Hi!
Thanks for the amazing work.

I try to denoise a point cloud, and this is the error that is printed to the screen:
"..../denoise/DMRDenoise/models/conv.py", line 54, in forward
    ], dim=-1)  # (B, N, K, d+c)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 24 and 20".

Each time I run the program, the same error appears but with different dimensions.
do you have any idea what could cause this problem?

thank you very much in advance! :)
Alavona

**Comment by alavona** [comment]
BTW, while the data set is about 50,000 points, my point clound contains around 2M points.

**Comment by luost26** [comment]
Could you upload one of your input point cloud files? Thanks!

**Comment by alavona** [comment]
Hi,
sure :)
[pointCloud.zip](https://github.com/luost26/DMRDenoise/files/7149056/pointCloud.zip)
