### ISSUE TITLE
A BUG

### ISSUE THREAD

**Issue by hewujunTDT** [luost26/DMRDenoise#17]
when i run  python denoise.py --input<> --output<> --ckpt ./pretrained/supervised/epoch=153.ckpt
i got this error
i run this program on google colab 
ubuntu 18.04

[INFO] Loading: ./pretrained/supervised/epoch=153.ckpt
Traceback (most recent call last):
  File "denoise.py", line 202, in <module>
    auto_denoise(args)
  File "denoise.py", line 140, in auto_denoise
    pc = np.loadtxt(args.input).astype(np.float32)
  File "/usr/local/envs/DMRDenoise/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1092, in loadtxt
    first_line = next(fh)
  File "/usr/local/envs/DMRDenoise/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

how to slove this problem

**Comment by luost26** [comment]
It seems that there is a weird character (0x80) in your input file, rather than a BUG in the program.

**Comment by hewujunTDT** [comment]
> It seems that there is a weird character (0x80) in your input file.

but the input file is /pretrained/supervised/epoch=153.ckpt i can not open it

**Comment by luost26** [comment]
> > It seems that there is a weird character (0x80) in your input file.
> 
> but the input file is /pretrained/supervised/epoch=153.ckpt i can not open it

It seems that the you put the model checkpoint to the place of input xyz file.
Your command seems to be incorrect: `python denoise.py --input<> --output<> --ckpt ./pretrained/supervised/epoch=153.ckpt`
If you have a noisy point cloud named `noisy.xyz`, and you want to name your denoise point cloud as `denoised.xyz`, the command shoud be:
```
python denoise.py --input noisy.xyz --output denoised.xyz --ckpt ./pretrained/supervised/epoch=153.ckpt
```

**Comment by luost26** [comment]
This model is a rather out-dated one. We recommend to try our latest model here: https://github.com/luost26/score-denoise

**Comment by hewujunTDT** [comment]
> python denoise.py --input noisy.xyz --output denoised.xyz --ckpt ./pretrained/supervised/epoch=153.ckpt

thanks slove problem
