### ISSUE TITLE
model does not support point clouds with less than 10K points

### ISSUE THREAD

**Issue by cleddy** [luost26/DMRDenoise#3]
The point cloud I want to denoise contains about 8k points. However, it seems you code does not support point clouds with less than 10K points. What can I do if I want to use your code to denoise my data?

**Comment by luost26** [comment]
On `denoise.py` line 167, set the hard-coded limit to 8k as follows:
```
    elif num_points >= 8000:
```
I think the pretrained model will work well for 8K points.

**Comment by GopiRajuMatta** [comment]
Hello,

My input has 2k points.
Kindly let me what are the modifications that should be made to retrain the model.

Thanks
Gopi

**Comment by luost26** [comment]
Hi Gopi,
 
Unfortunately, I think 2k point clouds are too sparse for the pretrained model to denoise them. I am sorry about that.

If you have to test DMRDenoise on 2k point clouds, you may make your own training set that contains 2k point clouds and train a model using it. (You may follow the [training set we provide](https://drive.google.com/drive/folders/1Qw_bYqsUcekeh165kgRODwIuYpsYIzM1) to make your own training set).

Thanks

**Comment by GopiRajuMatta** [comment]
Thank you for your apt response Luo.

I will down sample the training set to make it sparse and then train the network using this data.

One more thing to add to this is that I tested my point cloud data which has 2k points with the pre-trained model, results are good enough. But when noise is quite high, it is not able to denoise well.

I will retrain as you've suggested and then see.

Thank you once again.
Gopi

**Comment by luost26** [comment]
Great!

If you have further questions, please let me know and I will try to help 😄 

Thanks

**Comment by Leerw** [comment]
> Thank you for your apt response Luo.
> 
> I will down sample the training set to make it sparse and then train the network using this data.
> 
> One more thing to add to this is that I tested my point cloud data which has 2k points with the pre-trained model, results are good enough. But when noise is quite high, it is not able to denoise well.
> 
> I will retrain as you've suggested and then see.
> 
> Thank you once again.
> Gopi

Hi, have you trained the sparse version? Could you please share you results?
