### ISSUE TITLE
Parameters of  the Score Function

### ISSUE THREAD

**Issue by LitterWindwind** [luost26/DMRDenoise#9]
Hi@luost26

In the process of down sampling, I didn't find the feature of the point and the parameter of the score function to cross multiply. 
I only found Gpool Function, which is similar to pooling. 
Can it help me to point out where the corresponding steps should be?

**Comment by luost26** [comment]
https://github.com/luost26/DMRDenoise/blob/290a9e7a62b0fc2bd0ee2b906df3d353edf0eef9/models/pool.py#L46

`x` is the feature, `y` is the score.


https://github.com/luost26/DMRDenoise/blob/290a9e7a62b0fc2bd0ee2b906df3d353edf0eef9/models/pool.py#L38

and this is the line where we obtain `y`. `self.p` is the scoring module with learnable parameters.

**Comment by LitterWindwind** [comment]
Thanks a lot!!! Because he's not matrix multiplication, I ignore it, and now I get it.
